# Generated by Django 2.2.4 on 2019-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=32)),
                ('content', models.CharField(default=None, max_length=141)),
            ],
        ),
    ]
