# Generated by Django 2.2.4 on 2019-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purr',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
