# Generated by Django 2.2.4 on 2019-08-30 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_purr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purr',
            name='author',
            field=models.CharField(default=None, max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
