# Generated by Django 2.2.4 on 2019-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20190823_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purr',
            name='author',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
