# Generated by Django 2.2.4 on 2019-08-31 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0003_auto_20190830_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purr',
            name='author',
        ),
        migrations.AddField(
            model_name='purr',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
