# Generated by Django 2.2.4 on 2019-08-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20190823_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='purr',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
