# Generated by Django 2.2.4 on 2019-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_purr_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purr',
            name='content',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
