# Generated by Django 2.2.4 on 2019-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_auto_20190823_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purr',
            name='content',
            field=models.CharField(default=None, max_length=141),
        ),
    ]
